Update patch set 5
Patch Set 5:

What is strange is that the traceback still starts with

java.lang.NullPointerException: [...] getPackageName()' on a null object reference at com.android.launcher3.Launcher.onClickAppShortcut(Launcher.java:3083)

but with the patch applied, getPackageName() is called on line 3085... Are there known cases where a patch which is said to be included by http://www.cmxlog.com/ is not in reality ? Or is it possible that debug symbols/whatever is used in Java could lag behind because of unsufficient cache wipe ?

Patch-set: 5