PredictiveAppsProvider: fix null pointer exception
If component is null, we call ComponentName#getPackageName() on a null
object reference.

Happened when opening an app while it was upgraded.

----------

Stacktrace:

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.ComponentName.getPackageName()' on a null object reference
    at com.android.launcher3.allapps.PredictiveAppsProvider.buildComponentString(PredictiveAppsProvider.java:99)
    at com.android.launcher3.allapps.PredictiveAppsProvider.updateComponentCount(PredictiveAppsProvider.java:32)
    at com.android.launcher3.Launcher.startActivitySafely(Launcher.java:2764)
    at com.android.launcher3.Launcher.startAppShortcutOrInfoActivity(Launcher.java:2520)
    at com.android.launcher3.Launcher.onClick(Launcher.java:2352)
    at android.view.View.performClick(View.java:6320)
    at android.view.View$PerformClick.run(View.java:25087)
    at android.os.Handler.handleCallback(Handler.java:869)
    at android.os.Handler.dispatchMessage(Handler.java:101)
    at android.os.Looper.loop(Looper.java:206)
    at android.app.ActivityThread.main(ActivityThread.java:6733)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)

----------

Issue: BUGBASH-1524
Change-Id: I970453f5da87c36e9915b8c0bbe9f1cd2302ec93
Signed-off-by: Alexander Martinz <amartinz@shiftphones.com>