Trebuchet: adaptive icon
Squashed with the following:

Author: Bruno Martins <bgcngm@gmail.com>
Date:   Sat Oct 5 23:00:56 2019 +0100

    Trebuchet: Bump min SDK to 26 as required for adaptive icons

    Addresses the following compilation error:

      packages/apps/Trebuchet/res/mipmap-anydpi/ic_launcher.xml: error: <adaptive-icon> elements require a sdk version of at least 26.

    Change-Id: I5684e917ef0b691d99e2e59fd742d7570dfd1007

Change-Id: I84662d7cb35ed751c61c6223dc02f256f5ab3311
Signed-off-by: Joey <joey@lineageos.org>