IconCache: fix nullpointer exceptions
LauncherActivityInfo's or resolved activities can be null.

Example crash:
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ComponentName android.content.pm.LauncherActivityInfo.getComponentName()' on a null object reference
    at com.android.launcher3.IconCache.getCacheEntry(IconCache.java:392)
    at com.android.launcher3.Launcher.startEdit(Launcher.java:3988)
    at com.android.launcher3.popup.SystemShortcut$AppEdit.lambda$-com_android_launcher3_popup_SystemShortcut$AppEdit_4399(SystemShortcut.java:115)
    at com.android.launcher3.popup.-$Lambda$_SMHeS1Apq5nUPo60kvmkZszeNE.$m$0
    at com.android.launcher3.popup.-$Lambda$_SMHeS1Apq5nUPo60kvmkZszeNE.onClick
    at android.view.View.performClick(View.java:6320)
    at android.view.View$PerformClick.run(View.java:25087)
    at android.os.Handler.handleCallback(Handler.java:869)
    at android.os.Handler.dispatchMessage(Handler.java:101)
    at android.os.Looper.loop(Looper.java:206)
    at android.app.ActivityThread.main(ActivityThread.java:6733)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)

Issue: SHIFTOS-SW-31
Change-Id: If5f027e3146b358036b1ac1a1e973467d4fca2c4
Signed-off-by: Alexander Martinz <amartinz@shiftphones.com>