Trebuchet: Bump min SDK to 26 as required for adaptive icons
Addresses the following compilation error:

  packages/apps/Trebuchet/res/mipmap-anydpi/ic_launcher.xml: error: <adaptive-icon> elements require a sdk version of at least 26.

Change-Id: I5684e917ef0b691d99e2e59fd742d7570dfd1007